name: immune-material-scRNA
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - scanpy
  - anndata
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter